using Microsoft.AspNetCore.Http;

namespace HajjVR.Services;

/// <summary>Lokalisasi ringan 3 bahasa: Indonesia (default), English, Arabic (RTL).</summary>
public class LocalizationService
{
    public event Action? OnChanged;
    private string _lang = "id";
    public string Lang
    {
        get => _lang;
        set { if (_lang != value && Table.ContainsKey(value)) { _lang = value; OnChanged?.Invoke(); } }
    }

    public bool IsRtl => _lang == "ar";

    /// <summary>Preferensi bahasa dibaca dari cookie (diset oleh JS saat ganti bahasa) supaya
    /// bahasa yang benar ter-render sejak halaman pertama (termasuk saat prerender).</summary>
    public LocalizationService(IHttpContextAccessor http)
    {
        var lang = http?.HttpContext?.Request.Cookies["hajjvr-lang"];
        if (lang is not null && Table.ContainsKey(lang)) _lang = lang;
    }

    public string this[string key] =>
        Table[_lang].TryGetValue(key, out var v) ? v :
        Table["id"].TryGetValue(key, out var d) ? d : key;

    public static readonly (string Code, string Name, string Flag)[] Languages =
        [("id", "Bahasa Indonesia", "🇮🇩"), ("en", "English", "🇬🇧"), ("ar", "العربية", "🇸🇦")];

    private static readonly Dictionary<string, Dictionary<string, string>> Table = new()
    {
        ["id"] = new()
        {
            ["app.title"] = "HajjVR — Simulator Haji & Umrah",
            ["app.subtitle"] = "Simulator Haji & Umrah",
            ["nav.home"] = "Beranda", ["nav.dashboard"] = "Dashboard", ["nav.simulation"] = "Simulasi 3D",
            ["nav.map"] = "Peta Interaktif", ["nav.rituals"] = "Panduan Manasik", ["nav.chat"] = "Haji Sule",
            ["nav.reports"] = "Laporan", ["nav.jamaah"] = "Data Jamaah", ["nav.leaderboard"] = "Papan Peringkat",
            ["nav.search"] = "Pencarian", ["nav.settings"] = "Pengaturan", ["nav.users"] = "Pengguna",
            ["nav.stress"] = "Stress Test", ["nav.login"] = "Masuk", ["nav.logout"] = "Keluar", ["nav.profile"] = "Profil",
            ["nav.groupSim"] = "Simulasi", ["nav.groupAsst"] = "Asisten", ["nav.groupComm"] = "Komunitas",
            ["nav.groupMgmt"] = "Manajemen", ["nav.groupSys"] = "Sistem",

            ["home.pageTitle"] = "HajjVR — Beranda",
            ["home.welcome"] = "Selamat datang di HajjVR",
            ["home.badge"] = "✦ Pengalaman Ibadah Virtual ✦",
            ["home.tagline"] = "Simulator Haji & Umrah 3D interaktif — belajar manasik dengan pengalaman imersif.",
            ["home.ctaStart"] = "🕋 Mulai Simulasi 3D",
            ["home.ctaChat"] = "💬 Tanya Haji Sule",
            ["home.ctaRituals"] = "📿 Panduan Manasik",
            ["home.ctaLogin"] = "🔑 Masuk untuk Memulai",
            ["home.explore"] = "Jelajahi Fitur",
            ["home.f1t"] = "Masjidil Haram 3D",
            ["home.f1d"] = "Ka'bah, area thawaf (mataf), lintasan sa'i Safa–Marwah, lengkap dengan simulasi ribuan jamaah bergerak secara real-time.",
            ["home.f2t"] = "Masjid Nabawi",
            ["home.f2d"] = "Jelajahi Raudhah, makam Nabi ﷺ, dan area ibadah dengan mode kamera orang pertama, ketiga, dan pandangan burung.",
            ["home.f3t"] = "Manasik Haji",
            ["home.f3d"] = "Wukuf di Arafah, mabit di Muzdalifah, dan lempar jumrah di Mina — semua ritual haji dalam satu simulasi interaktif.",
            ["home.f4t"] = "Chatbot Haji Sule",
            ["home.f4d"] = "Asisten AI multi-model (OpenAI, Anthropic, Gemini, Ollama) yang paham manasik, bisa cari internet, hitung, dan query data jamaah.",
            ["home.f5t"] = "Dashboard & Laporan",
            ["home.f5d"] = "Statistik jamaah, heatmap keramaian, progres ibadah, dan ekspor laporan ke PDF/Excel untuk pembimbing dan operator.",
            ["home.f6t"] = "Gamifikasi",
            ["home.f6d"] = "Kumpulkan badge, pantau progres, dan bersaing sehat di papan peringkat jamaah.",
            ["home.demo"] = "💡 Akun demo:",

            ["login.pageTitle"] = "Masuk — HajjVR",
            ["login.title"] = "Masuk",
            ["login.subtitle"] = "Simulator Haji & Umrah 3D",
            ["login.username"] = "Username",
            ["login.password"] = "Password",
            ["login.usernamePh"] = "mis. admin",
            ["login.submit"] = "🔑 Masuk",
            ["login.forgot"] = "Lupa password?",
            ["login.error"] = "Username atau password salah.",
            ["login.demo"] = "Demo:",

            ["fp.pageTitle"] = "Reset Password — HajjVR",
            ["fp.title"] = "🔐 Lupa Password",
            ["fp.hint"] = "Masukkan username atau email. Dalam mode demo, tautan reset ditampilkan langsung di sini (tanpa email).",
            ["fp.identity"] = "Username / Email",
            ["fp.identityPh"] = "mis. jamaah01",
            ["fp.submit"] = "Buat Tautan Reset",
            ["fp.created"] = "✅ Tautan reset dibuat (berlaku 1 jam):",
            ["fp.notFound"] = "❌ Pengguna tidak ditemukan.",
            ["fp.back"] = "← Kembali ke login",

            ["rp.pageTitle"] = "Password Baru — HajjVR",
            ["rp.title"] = "🔑 Setel Password Baru",
            ["rp.done"] = "✅ Password berhasil diubah.",
            ["rp.loginNow"] = "Masuk sekarang →",
            ["rp.token"] = "Token Reset",
            ["rp.newPassword"] = "Password Baru (min. 6 karakter)",
            ["rp.submit"] = "Simpan Password",
            ["rp.error"] = "❌ Token tidak valid/kedaluwarsa, atau password terlalu pendek.",

            ["sim.pageTitle"] = "Simulasi 3D — HajjVR",
            ["sim.title"] = "🕶️ Simulasi 3D",
            ["sim.badge"] = "🕐 {0} · {1} FPS · {2} jamaah",
            ["sim.hud"] = "FPS: {0} · Jamaah: {1} · Draw: {2} · 🕐 {3}",
            ["sim.sceneHaram"] = "🕋 Masjidil Haram",
            ["sim.sceneNabawi"] = "🕌 Masjid Nabawi",
            ["sim.sceneManasik"] = "⛰️ Manasik Haji",
            ["sim.focus"] = "Fokus:",
            ["sim.timeLabel"] = "Jam simulasi",
            ["sim.camOrbit"] = "🎥 Orbit", ["sim.camBird"] = "🦅 Bird-eye",
            ["sim.camFp"] = "👁️ Orang-1", ["sim.camTp"] = "🚶 Orang-3",
            ["sim.resetCam"] = "🎯 Reset",
            ["sim.fullscreen"] = "⛶ Fullscreen",
            ["sim.tSubuh"] = "🌅 Subuh", ["sim.tSiang"] = "☀️ Siang",
            ["sim.tMaghrib"] = "🌇 Maghrib", ["sim.tMalam"] = "🌙 Malam",
            ["sim.autoCycle"] = "🔄 Siklus 24 Jam",
            ["sim.stopCycle"] = "⏹ Stop Siklus",
            ["sim.crowd"] = "👥 Jamaah:",
            ["sim.speed"] = "⏩ Kecepatan:",
            ["sim.pause"] = "⏸ Jeda", ["sim.resume"] = "▶ Lanjut",
            ["sim.shadowsOn"] = "🌗 Bayangan: ON", ["sim.shadowsOff"] = "🌗 Bayangan: OFF",
            ["sim.guide"] = "📖 Panduan", ["sim.controls"] = "⌨️ Kontrol",
            ["sim.controlsTitle"] = "⌨️ Kontrol",
            ["sim.bOrbit"] = "Orbit", ["sim.bFp"] = "Orang pertama", ["sim.bTp"] = "Orang ketiga", ["sim.bVr"] = "VR",
            ["sim.helpOrbit"] = "seret = putar, scroll = zoom, klik kanan = geser",
            ["sim.helpFp"] = "klik kanvas → WASD/panah jalan, Shift lari, Esc keluar",
            ["sim.helpTp"] = "otomatis mengikuti satu jamaah",
            ["sim.helpVr"] = "tombol \"Enter VR\" di bawah (headset WebXR)",
            ["sim.guideHaram"] = "🕋 Thawaf & Sa'i",
            ["sim.guideNabawi"] = "🕌 Ziarah Masjid Nabawi",
            ["sim.guideManasik"] = "⛰️ Rangkaian Haji",
            ["sim.h1"] = "Mulai thawaf dari garis coklat sejajar Hajar Aswad (sudut timur Ka'bah), Ka'bah di kiri.",
            ["sim.h2"] = "Kelilingi Ka'bah 7 putaran berlawanan arah jarum jam.",
            ["sim.h3"] = "Shalat 2 rakaat di belakang Maqam Ibrahim (kubah kristal emas).",
            ["sim.h4"] = "Minum air zamzam.",
            ["sim.h5"] = "Sa'i: galeri panjang di sisi timur — dari Safa (tenggara) ke Marwah (timur laut), 7 lintasan.",
            ["sim.h6"] = "Lari kecil di antara dua lampu hijau di tengah galeri (untuk laki-laki).",
            ["sim.n1"] = "Masuk masjid dengan kaki kanan, baca doa masuk masjid.",
            ["sim.n2"] = "Shalat tahiyatul masjid 2 rakaat.",
            ["sim.n3"] = "Menuju Raudhah (zona hijau, dekat Kubah Hijau) bila memungkinkan.",
            ["sim.n4"] = "Ucapkan salam kepada Nabi ﷺ, Abu Bakar, dan Umar dengan tenang.",
            ["sim.m1"] = "8 Dzulhijjah: menuju Mina (kota tenda di timur), mabit.",
            ["sim.m2"] = "9 Dzulhijjah: wukuf di Arafah (barat, dekat Jabal Rahmah) hingga maghrib.",
            ["sim.m3"] = "Malam 10: mabit di Muzdalifah, kumpulkan 49–70 kerikil.",
            ["sim.m4"] = "10 Dzulhijjah: lempar Jumrah Aqabah di jembatan Jamarat, tahalul.",
            ["sim.m5"] = "11–13 Dzulhijjah: mabit di Mina, lempar tiga jumrah tiap hari.",

            ["dash.pageTitle"] = "Dashboard — HajjVR",
            ["dash.autoRefresh"] = "🔄 Auto-refresh 30 detik",
            ["dash.mentors"] = "{0} pembimbing",
            ["dash.hajiDone"] = "{0} haji selesai",
            ["dash.chatSessions"] = "{0} sesi chat",
            ["dash.done"] = "Selesai", ["dash.inProgress"] = "Berjalan", ["dash.notStarted"] = "Belum",
            ["dash.crowdNow"] = "👥 Keramaian Saat Ini",
            ["dash.heatmapTitle"] = "🔥 Heatmap Keramaian (24 jam)",
            ["dash.people"] = "orang",

            ["rituals.pageTitle"] = "Panduan Manasik — HajjVR",
            ["rituals.title"] = "📿 Panduan Manasik Interaktif",
            ["rituals.umrah"] = "🌙 Umrah", ["rituals.haji"] = "🏔️ Haji",
            ["rituals.newBadge"] = "🎉 Badge baru!",
            ["rituals.overall"] = "Progres keseluruhan",
            ["rituals.progressFmt"] = "{0} dari {1} ritual {2} selesai ({3}%)",
            ["rituals.wordU"] = "umrah", ["rituals.wordH"] = "haji",
            ["rituals.start"] = "▶ Mulai", ["rituals.markDone"] = "✔ Tandai Selesai", ["rituals.repeat"] = "↺ Ulangi",
            ["rituals.u1t"] = "1. Ihram dari Miqat",
            ["rituals.u1d"] = "Mandi, memakai pakaian ihram (2 kain tanpa jahitan bagi pria), niat umrah dari miqat (mis. Bir Ali untuk yang dari Madinah). Jauhi larangan ihram.",
            ["rituals.u2t"] = "2. Thawaf 7 Putaran",
            ["rituals.u2d"] = "Mengelilingi Ka'bah 7 kali berlawanan arah jarum jam, mulai dari garis Hajar Aswad, Ka'bah di sebelah kiri. Sunnah raml (lari kecil) 3 putaran pertama bagi pria.",
            ["rituals.u3t"] = "3. Sa'i Safa–Marwah",
            ["rituals.u3d"] = "Berjalan 7 lintasan dari Safa ke Marwah (± 3,15 km total). Berlari kecil di antara dua lampu hijau bagi pria. Diakhiri di Marwah.",
            ["rituals.u4t"] = "4. Tahalul",
            ["rituals.u4d"] = "Mencukur habis (afdhal bagi pria) atau memendekkan rambut minimal 3 helai. Umrah selesai — larangan ihram kembali halal.",
            ["rituals.u5t"] = "5. Ziarah Madinah (Sunnah)",
            ["rituals.u5d"] = "Shalat di Masjid Nabawi (bernilai 1000x), doa di Raudhah, salam kepada Nabi ﷺ. Bukan bagian dari rukun umrah, namun sangat dianjurkan.",
            ["rituals.h1t"] = "1. Ihram Haji (8 Dzulhijjah)",
            ["rituals.h1d"] = "Niat haji dari tempat menginap (bagi tamattu'), berangkat ke Mina untuk mabit hari Tarwiyah.",
            ["rituals.h2t"] = "2. Wukuf di Arafah (9 Dzulhijjah)",
            ["rituals.h2d"] = "Rukun terpenting — 'Haji adalah Arafah'. Dari tergelincir matahari hingga maghrib. Perbanyak doa, dzikir, dan istighfar.",
            ["rituals.h3t"] = "3. Mabit di Muzdalifah",
            ["rituals.h3d"] = "Bermalam setelah maghrib hingga lewat tengah malam. Kumpulkan 49–70 butir kerikil untuk lempar jumrah.",
            ["rituals.h4t"] = "4. Lempar Jumrah",
            ["rituals.h4d"] = "10 Dzulhijjah: Jumrah Aqabah 7 batu. 11–13 Dzulhijjah: tiga jumrah (Ula, Wustha, Aqabah) masing-masing 7 batu setelah zawal.",
            ["rituals.h5t"] = "5. Mabit di Mina (Hari Tasyrik)",
            ["rituals.h5d"] = "Bermalam di Mina pada malam 11, 12 (nafar awal) atau hingga 13 Dzulhijjah (nafar tsani).",
            ["rituals.h6t"] = "6. Thawaf Ifadah",
            ["rituals.h6d"] = "Rukun haji — thawaf 7 putaran setelah tahalul awal, dilanjutkan sa'i haji (bagi tamattu').",
            ["rituals.h7t"] = "7. Thawaf Wada'",
            ["rituals.h7d"] = "Thawaf perpisahan sebelum meninggalkan Makkah. Wajib haji bagi yang bukan penduduk Makkah.",

            ["rit.Ihram"] = "Ihram & Niat", ["rit.Thawaf"] = "Thawaf", ["rit.Sai"] = "Sa'i",
            ["rit.Tahalul"] = "Tahalul", ["rit.WukufArafah"] = "Wukuf di Arafah",
            ["rit.MabitMuzdalifah"] = "Mabit Muzdalifah", ["rit.LemparJumrah"] = "Lempar Jumrah",
            ["rit.MabitMina"] = "Mabit Mina", ["rit.ThawafIfadah"] = "Thawaf Ifadah",
            ["rit.ThawafWada"] = "Thawaf Wada'", ["rit.ZiarahNabawi"] = "Ziarah Nabawi",
            ["zone.mataf"] = "Area Thawaf (Mataf)", ["zone.masaa"] = "Area Sa'i (Mas'a)",
            ["zone.mosque"] = "Masjidil Haram", ["zone.arafah"] = "Padang Arafah",
            ["zone.muzdalifah"] = "Muzdalifah", ["zone.mina"] = "Mina / Jamarat",
            ["zone.nabawi"] = "Masjid Nabawi", ["zone.raudhah"] = "Raudhah",

            ["chat.pageTitle"] = "Haji Sule — HajjVR",
            ["chat.subtitle"] = "asisten ibadah Anda",
            ["chat.modelActive"] = "Model aktif",
            ["chat.newSession"] = "➕ Sesi Baru",
            ["chat.deleteSession"] = "Hapus sesi",
            ["chat.resetSession"] = "🧹 Reset Sesi Ini",
            ["chat.greeting"] = "Assalamu'alaikum! Sule di sini, siap membantu!",
            ["chat.greetingText"] = "Tanya apa saja: tata cara thawaf, doa sa'i, keramaian mataf sekarang, progres jamaah, kurs, sampai berita terkini. Lampirkan gambar/dokumen kalau perlu.",
            ["chat.you"] = "🙋 Anda",
            ["chat.attach"] = "Lampirkan gambar/dokumen",
            ["chat.placeholder"] = "Tulis pertanyaan… (Enter untuk kirim, Shift+Enter baris baru)",
            ["chat.newTitle"] = "Percakapan Baru",

            ["map.pageTitle"] = "Peta Interaktif — HajjVR",
            ["map.title"] = "🗺️ Peta Interaktif",
            ["map.makkah"] = "🕋 Makkah", ["map.madinah"] = "🕌 Madinah",
            ["map.open3d"] = "🕶️ Buka Mode 3D",
            ["map.catMasjid"] = "Masjid", ["map.catRitual"] = "Ritual", ["map.catZiarah"] = "Ziarah", ["map.catFacility"] = "Fasilitas",
            ["map.selectHint"] = "👆 Klik salah satu titik lokasi di peta untuk melihat detail.",
            ["map.viewIn3d"] = "🕶️ Lihat di 3D",
            ["map.allLocations"] = "📍 Semua Lokasi",

            ["search.pageTitle"] = "Pencarian — HajjVR",
            ["search.title"] = "🔎 Pencarian Semantik",
            ["search.subtitle"] = "Cari panduan manasik, lokasi suci, dan dokumen.",
            ["search.modeVec"] = "Mode: embedding vektor 🧠",
            ["search.modeKw"] = "Mode: kata kunci (set Embedding:ApiKey untuk mode vektor)",
            ["search.placeholder"] = "mis. bagaimana tata cara thawaf? apa itu raudhah?",
            ["search.noResults"] = "Tidak ada hasil untuk",
            ["search.score"] = "skor",

            ["lb.pageTitle"] = "Papan Peringkat — HajjVR",
            ["lb.title"] = "🏆 Papan Peringkat Jamaah",
            ["lb.subtitle"] = "Poin = poin badge + 10 poin per ritual selesai. Semangat beribadah, bukan sekadar bersaing! 😊",
            ["lb.name"] = "Nama", ["lb.group"] = "Rombongan", ["lb.badge"] = "Badge",
            ["lb.ritualsDone"] = "Ritual Selesai", ["lb.points"] = "Poin",

            ["rep.pageTitle"] = "Laporan — HajjVR",
            ["rep.title"] = "📑 Laporan Perjalanan Jamaah",
            ["rep.searchPh"] = "Cari nama jamaah…",
            ["rep.allGroups"] = "Semua rombongan",
            ["rep.name"] = "Nama", ["rep.group"] = "Rombongan", ["rep.package"] = "Paket",
            ["rep.progress"] = "Progres",
            ["rep.downloadPdf"] = "Unduh laporan PDF individu",

            ["jl.pageTitle"] = "Data Jamaah — HajjVR",
            ["jl.title"] = "🧕 Data Jamaah",
            ["jl.searchPh"] = "Cari nama / rombongan…",
            ["jl.name"] = "Nama", ["jl.username"] = "Username", ["jl.group"] = "Rombongan", ["jl.package"] = "Paket",
            ["jl.nationality"] = "Kebangsaan", ["jl.phone"] = "Telepon",
            ["jl.detail"] = "Detail →",

            ["jd.pageTitle"] = "Detail Jamaah — HajjVR",
            ["jd.pdf"] = "📄 Laporan PDF",
            ["jd.profile"] = "Profil", ["jd.group"] = "Rombongan", ["jd.package"] = "Paket",
            ["jd.passport"] = "No. Paspor", ["jd.nationality"] = "Kebangsaan", ["jd.phone"] = "Telepon",
            ["jd.notes"] = "Catatan", ["jd.save"] = "💾 Simpan", ["jd.saved"] = "✅ Tersimpan",
            ["jd.progress"] = "Progres Ritual",
            ["jd.docs"] = "📂 Dokumen & Lampiran", ["jd.upload"] = "⬆️ Unggah Dokumen",
            ["jd.colTitle"] = "Judul", ["jd.colType"] = "Jenis", ["jd.colSize"] = "Ukuran", ["jd.colUploaded"] = "Diunggah",
            ["jd.kindImg"] = "Gambar", ["jd.kindVideo"] = "Video", ["jd.kindDoc"] = "Dokumen",

            ["prof.pageTitle"] = "Profil — HajjVR",
            ["prof.title"] = "👤 Profil Saya",
            ["prof.bio"] = "Data Diri", ["prof.fullName"] = "Nama Lengkap", ["prof.email"] = "Email",
            ["prof.avatar"] = "Foto Profil", ["prof.save"] = "💾 Simpan", ["prof.saved"] = "✅ Tersimpan",
            ["prof.changePass"] = "Ganti Password", ["prof.oldPass"] = "Password Lama",
            ["prof.newPass"] = "Password Baru (min. 6)", ["prof.changePassBtn"] = "🔐 Ganti Password",
            ["prof.passShort"] = "❌ Password baru minimal 6 karakter.",
            ["prof.passOk"] = "✅ Password berhasil diganti.",
            ["prof.passWrong"] = "❌ Password lama salah.",
            ["prof.badges"] = "🏅 Badge Saya", ["prof.points"] = "poin",

            ["sett.pageTitle"] = "Pengaturan — HajjVR",
            ["sett.title"] = "⚙️ Pengaturan Aplikasi",
            ["sett.subtitle"] = "Nilai di sini menimpa appsettings.json (tersimpan di database, berlaku tanpa restart).",
            ["sett.llm"] = "🧠 Model AI (Haji Sule)",
            ["sett.provider"] = "Provider", ["sett.model"] = "Model", ["sett.apiKey"] = "API Key",
            ["sett.endpoint"] = "Endpoint (opsional, OpenAI-compatible)",
            ["sett.temperature"] = "Temperature", ["sett.maxTokens"] = "Max Tokens",
            ["sett.systemPrompt"] = "System Prompt (persona Haji Sule)",
            ["sett.sysPromptPh"] = "Kosongkan untuk persona bawaan",
            ["sett.storage"] = "📦 Penyimpanan File",
            ["sett.storageFs"] = "File System (default)",
            ["sett.azureCs"] = "Connection String",
            ["sett.accessKey"] = "Access Key", ["sett.secretKey"] = "Secret Key",
            ["sett.bucket"] = "Bucket", ["sett.serviceUrl"] = "Service URL (MinIO)",
            ["sett.integration"] = "🔌 Integrasi",
            ["sett.tavily"] = "Tavily API Key (pencarian internet chatbot)",
            ["sett.restKey"] = "API Key REST (header X-Api-Key)",
            ["sett.embeddingKey"] = "Embedding API Key (pencarian semantik vektor)",
            ["sett.embeddingPh"] = "kosong = mode kata kunci",
            ["sett.dbActive"] = "🗄️ Database aktif:",
            ["sett.dbChange"] = "Ganti provider database lewat appsettings.json → Database:Provider (SQLite / SQLServer / MySQL / PostgreSQL) lalu restart aplikasi.",
            ["sett.saveAll"] = "💾 Simpan Semua",
            ["sett.saved"] = "✅ Tersimpan & langsung aktif",

            ["users.pageTitle"] = "Pengguna — HajjVR",
            ["users.title"] = "👥 Manajemen Pengguna",
            ["users.newUser"] = "➕ Pengguna Baru",
            ["users.newUserTitle"] = "Pengguna Baru",
            ["users.username"] = "Username", ["users.fullName"] = "Nama lengkap", ["users.email"] = "Email", ["users.password"] = "Password",
            ["users.allRoles"] = "Semua role",
            ["users.name"] = "Nama", ["users.role"] = "Role", ["users.status"] = "Status", ["users.created"] = "Dibuat",
            ["users.active"] = "Aktif", ["users.inactive"] = "Nonaktif",
            ["users.errRequired"] = "Username wajib diisi & password minimal 6 karakter.",
            ["users.errExists"] = "Username sudah dipakai.",

            ["st.pageTitle"] = "Stress Test — HajjVR",
            ["st.title"] = "⚡ Stress Test Crowd Simulation",
            ["st.subtitle"] = "Uji performa render ribuan jamaah paralel. Naikkan jumlah agen sampai FPS turun untuk mengetahui batas perangkat.",
            ["st.fpsHistory"] = "📉 Riwayat FPS (60 detik)",

            ["nf.title"] = "Halaman Tidak Ditemukan",
            ["nf.desc"] = "Maaf, konten yang Anda cari tidak ada.",
            ["nf.home"] = "← Kembali ke Beranda",

            ["err.title"] = "Error.",
            ["err.msg"] = "Terjadi kesalahan saat memproses permintaan Anda.",
            ["err.requestId"] = "Request ID:",

            ["rc.rejoining"] = "Menghubungkan kembali ke server...",
            ["rc.rejoinFail"] = "Gagal terhubung kembali... mencoba lagi dalam <span id=\"components-seconds-to-next-attempt\"></span> detik.",
            ["rc.failed"] = "Gagal terhubung kembali.<br />Silakan coba lagi atau muat ulang halaman.",
            ["rc.retry"] = "Coba Lagi",
            ["rc.paused"] = "Sesi dijeda oleh server.",
            ["rc.resumeFailed"] = "Gagal melanjutkan sesi.<br />Silakan coba lagi atau muat ulang halaman.",
            ["rc.resume"] = "Lanjutkan",

            ["errUi.title"] = "Terjadi kesalahan tak terduga.",
            ["errUi.reload"] = "Muat ulang",

            ["common.save"] = "Simpan", ["common.cancel"] = "Batal", ["common.delete"] = "Hapus",
            ["common.search"] = "Cari", ["common.export.pdf"] = "Ekspor PDF", ["common.export.excel"] = "Ekspor Excel",
            ["common.openMenu"] = "Buka menu", ["common.theme"] = "Ganti tema", ["common.profile"] = "Profil",
            ["common.language"] = "Pilih bahasa",
            ["common.loading"] = "Memuat…", ["common.back"] = "← Kembali",
            ["dash.totalJamaah"] = "Total Jamaah", ["dash.avgProgress"] = "Rata-rata Progres",
            ["dash.completedUmrah"] = "Umrah Selesai", ["dash.activeNow"] = "Aktivitas 24 Jam",
            ["dash.heatmap"] = "Heatmap Keramaian", ["dash.progressByRitual"] = "Progres per Ritual",
        },
        ["en"] = new()
        {
            ["app.title"] = "HajjVR — Hajj & Umrah Simulator",
            ["app.subtitle"] = "Hajj & Umrah Simulator",
            ["nav.home"] = "Home", ["nav.dashboard"] = "Dashboard", ["nav.simulation"] = "3D Simulation",
            ["nav.map"] = "Interactive Map", ["nav.rituals"] = "Ritual Guide", ["nav.chat"] = "Haji Sule",
            ["nav.reports"] = "Reports", ["nav.jamaah"] = "Pilgrims", ["nav.leaderboard"] = "Leaderboard",
            ["nav.search"] = "Search", ["nav.settings"] = "Settings", ["nav.users"] = "Users",
            ["nav.stress"] = "Stress Test", ["nav.login"] = "Sign In", ["nav.logout"] = "Sign Out", ["nav.profile"] = "Profile",
            ["nav.groupSim"] = "Simulation", ["nav.groupAsst"] = "Assistant", ["nav.groupComm"] = "Community",
            ["nav.groupMgmt"] = "Management", ["nav.groupSys"] = "System",

            ["home.pageTitle"] = "HajjVR — Home",
            ["home.welcome"] = "Welcome to HajjVR",
            ["home.badge"] = "✦ Virtual Worship Experience ✦",
            ["home.tagline"] = "Interactive 3D Hajj & Umrah simulator — learn the rituals through an immersive experience.",
            ["home.ctaStart"] = "🕋 Start 3D Simulation",
            ["home.ctaChat"] = "💬 Ask Haji Sule",
            ["home.ctaRituals"] = "📿 Ritual Guide",
            ["home.ctaLogin"] = "🔑 Sign In to Start",
            ["home.explore"] = "Explore Features",
            ["home.f1t"] = "Masjid al-Haram 3D",
            ["home.f1d"] = "The Ka'bah, the tawaf area (mataf), and the Sa'i course from Safa to Marwah, with real-time simulation of thousands of pilgrims.",
            ["home.f2t"] = "Masjid an-Nabawi",
            ["home.f2d"] = "Explore the Rawdah, the Prophet's ﷺ tomb, and worship areas with first-person, third-person, and bird's-eye camera modes.",
            ["home.f3t"] = "Hajj Manasik",
            ["home.f3d"] = "Standing at Arafah, overnight at Muzdalifah, and stoning the jamarat in Mina — all Hajj rituals in one interactive simulation.",
            ["home.f4t"] = "Haji Sule Chatbot",
            ["home.f4d"] = "A multi-model AI assistant (OpenAI, Anthropic, Gemini, Ollama) that knows the rituals, can search the web, do math, and query pilgrim data.",
            ["home.f5t"] = "Dashboard & Reports",
            ["home.f5d"] = "Pilgrim statistics, crowd heatmaps, worship progress, and report export to PDF/Excel for guides and operators.",
            ["home.f6t"] = "Gamification",
            ["home.f6d"] = "Collect badges, track progress, and compete on the pilgrim leaderboard.",
            ["home.demo"] = "💡 Demo accounts:",

            ["login.pageTitle"] = "Sign In — HajjVR",
            ["login.title"] = "Sign In",
            ["login.subtitle"] = "Hajj & Umrah 3D Simulator",
            ["login.username"] = "Username",
            ["login.password"] = "Password",
            ["login.usernamePh"] = "e.g. admin",
            ["login.submit"] = "🔑 Sign In",
            ["login.forgot"] = "Forgot password?",
            ["login.error"] = "Incorrect username or password.",
            ["login.demo"] = "Demo:",

            ["fp.pageTitle"] = "Reset Password — HajjVR",
            ["fp.title"] = "🔐 Forgot Password",
            ["fp.hint"] = "Enter your username or email. In demo mode the reset link is shown right here (no email is sent).",
            ["fp.identity"] = "Username / Email",
            ["fp.identityPh"] = "e.g. jamaah01",
            ["fp.submit"] = "Create Reset Link",
            ["fp.created"] = "✅ Reset link created (valid for 1 hour):",
            ["fp.notFound"] = "❌ User not found.",
            ["fp.back"] = "← Back to sign in",

            ["rp.pageTitle"] = "New Password — HajjVR",
            ["rp.title"] = "🔑 Set New Password",
            ["rp.done"] = "✅ Password changed successfully.",
            ["rp.loginNow"] = "Sign in now →",
            ["rp.token"] = "Reset Token",
            ["rp.newPassword"] = "New Password (min. 6 characters)",
            ["rp.submit"] = "Save Password",
            ["rp.error"] = "❌ Invalid/expired token, or password too short.",

            ["sim.pageTitle"] = "3D Simulation — HajjVR",
            ["sim.title"] = "🕶️ 3D Simulation",
            ["sim.badge"] = "🕐 {0} · {1} FPS · {2} pilgrims",
            ["sim.hud"] = "FPS: {0} · Pilgrims: {1} · Draw: {2} · 🕐 {3}",
            ["sim.sceneHaram"] = "🕋 Masjid al-Haram",
            ["sim.sceneNabawi"] = "🕌 Masjid an-Nabawi",
            ["sim.sceneManasik"] = "⛰️ Hajj Manasik",
            ["sim.focus"] = "Focus:",
            ["sim.timeLabel"] = "Simulation time",
            ["sim.camOrbit"] = "🎥 Orbit", ["sim.camBird"] = "🦅 Bird-eye",
            ["sim.camFp"] = "👁️ 1st-Person", ["sim.camTp"] = "🚶 3rd-Person",
            ["sim.resetCam"] = "🎯 Reset",
            ["sim.fullscreen"] = "⛶ Fullscreen",
            ["sim.tSubuh"] = "🌅 Dawn", ["sim.tSiang"] = "☀️ Noon",
            ["sim.tMaghrib"] = "🌇 Sunset", ["sim.tMalam"] = "🌙 Night",
            ["sim.autoCycle"] = "🔄 24h Cycle",
            ["sim.stopCycle"] = "⏹ Stop Cycle",
            ["sim.crowd"] = "👥 Crowd:",
            ["sim.speed"] = "⏩ Speed:",
            ["sim.pause"] = "⏸ Pause", ["sim.resume"] = "▶ Resume",
            ["sim.shadowsOn"] = "🌗 Shadows: ON", ["sim.shadowsOff"] = "🌗 Shadows: OFF",
            ["sim.guide"] = "📖 Guide", ["sim.controls"] = "⌨️ Controls",
            ["sim.controlsTitle"] = "⌨️ Controls",
            ["sim.bOrbit"] = "Orbit", ["sim.bFp"] = "First-person", ["sim.bTp"] = "Third-person", ["sim.bVr"] = "VR",
            ["sim.helpOrbit"] = "drag = rotate, scroll = zoom, right-click = pan",
            ["sim.helpFp"] = "click canvas → WASD/arrows to walk, Shift to run, Esc to exit",
            ["sim.helpTp"] = "automatically follows one pilgrim",
            ["sim.helpVr"] = "\"Enter VR\" button below (WebXR headset)",
            ["sim.guideHaram"] = "🕋 Tawaf & Sa'i",
            ["sim.guideNabawi"] = "🕌 Visiting Masjid an-Nabawi",
            ["sim.guideManasik"] = "⛰️ Hajj Sequence",
            ["sim.h1"] = "Start tawaf from the brown line aligned with the Black Stone (east corner of the Ka'bah), keeping the Ka'bah on your left.",
            ["sim.h2"] = "Circle the Ka'bah 7 times counterclockwise.",
            ["sim.h3"] = "Pray 2 raka'at behind Maqam Ibrahim (gold crystal dome).",
            ["sim.h4"] = "Drink zamzam water.",
            ["sim.h5"] = "Sa'i: long gallery on the east side — from Safa (southeast) to Marwah (northeast), 7 laps.",
            ["sim.h6"] = "Jog between the two green lights in the middle of the gallery (for men).",
            ["sim.n1"] = "Enter the mosque with your right foot and recite the entry dua.",
            ["sim.n2"] = "Pray 2 raka'at tahiyatul masjid.",
            ["sim.n3"] = "Head to the Rawdah (green zone, near the Green Dome) if possible.",
            ["sim.n4"] = "Calmly send salutations to the Prophet ﷺ, Abu Bakr, and Umar.",
            ["sim.m1"] = "8 Dhu al-Hijjah: head to Mina (tent city to the east), overnight stay.",
            ["sim.m2"] = "9 Dhu al-Hijjah: stand at Arafah (west, near Jabal al-Rahmah) until sunset.",
            ["sim.m3"] = "Night of 10: overnight at Muzdalifah, collect 49–70 pebbles.",
            ["sim.m4"] = "10 Dhu al-Hijjah: stone the Jamrat al-Aqabah at the Jamarat bridge, then tahallul.",
            ["sim.m5"] = "11–13 Dhu al-Hijjah: overnight in Mina, stone the three jamarat each day.",

            ["dash.pageTitle"] = "Dashboard — HajjVR",
            ["dash.autoRefresh"] = "🔄 Auto-refresh 30s",
            ["dash.mentors"] = "{0} guides",
            ["dash.hajiDone"] = "{0} hajj completed",
            ["dash.chatSessions"] = "{0} chat sessions",
            ["dash.done"] = "Done", ["dash.inProgress"] = "In progress", ["dash.notStarted"] = "Not started",
            ["dash.crowdNow"] = "👥 Current Crowd",
            ["dash.heatmapTitle"] = "🔥 Crowd Heatmap (24h)",
            ["dash.people"] = "people",

            ["rituals.pageTitle"] = "Ritual Guide — HajjVR",
            ["rituals.title"] = "📿 Interactive Ritual Guide",
            ["rituals.umrah"] = "🌙 Umrah", ["rituals.haji"] = "🏔️ Hajj",
            ["rituals.newBadge"] = "🎉 New badge!",
            ["rituals.overall"] = "Overall progress",
            ["rituals.progressFmt"] = "{0} of {1} {2} rituals completed ({3}%)",
            ["rituals.wordU"] = "umrah", ["rituals.wordH"] = "hajj",
            ["rituals.start"] = "▶ Start", ["rituals.markDone"] = "✔ Mark Done", ["rituals.repeat"] = "↺ Repeat",
            ["rituals.u1t"] = "1. Ihram from the Miqat",
            ["rituals.u1d"] = "Take a bath, put on ihram garments (two seamless cloths for men), and intend umrah from the miqat (e.g. Bir Ali for those coming from Madinah). Avoid the ihram prohibitions.",
            ["rituals.u2t"] = "2. Tawaf – 7 Circuits",
            ["rituals.u2d"] = "Circle the Ka'bah 7 times counterclockwise, starting from the Black Stone line with the Ka'bah on your left. It is sunnah for men to do raml (fast pace) in the first 3 circuits.",
            ["rituals.u3t"] = "3. Sa'i between Safa and Marwah",
            ["rituals.u3d"] = "Walk 7 laps from Safa to Marwah (±3.15 km in total). Men jog between the two green lights. End at Marwah.",
            ["rituals.u4t"] = "4. Tahallul",
            ["rituals.u4d"] = "Shave the head (preferred for men) or shorten the hair by at least 3 strands. Umrah is complete — ihram restrictions are lifted.",
            ["rituals.u5t"] = "5. Visit to Madinah (Sunnah)",
            ["rituals.u5d"] = "Pray at Masjid an-Nabawi (worth 1000 prayers), make dua in the Rawdah, and greet the Prophet ﷺ. Not part of the pillars of umrah, but highly recommended.",
            ["rituals.h1t"] = "1. Hajj Ihram (8 Dhu al-Hijjah)",
            ["rituals.h1d"] = "Intend hajj from your accommodation (for tamattu'), then head to Mina to spend the night of Tarwiyah.",
            ["rituals.h2t"] = "2. Standing at Arafah (9 Dhu al-Hijjah)",
            ["rituals.h2d"] = "The most important pillar — 'Hajj is Arafah'. From noon until sunset. Increase dua, dhikr, and istighfar.",
            ["rituals.h3t"] = "3. Overnight at Muzdalifah",
            ["rituals.h3d"] = "Stay overnight after Maghrib past midnight. Collect 49–70 pebbles for stoning the jamarat.",
            ["rituals.h4t"] = "4. Stoning the Jamarat",
            ["rituals.h4d"] = "10 Dhu al-Hijjah: stone Jamrat al-Aqabah with 7 pebbles. 11–13 Dhu al-Hijjah: stone the three jamarat (Ula, Wustha, Aqabah), 7 each after zawal.",
            ["rituals.h5t"] = "5. Overnight in Mina (Days of Tashreeq)",
            ["rituals.h5d"] = "Spend the nights of 11, 12 (first departure) or until 13 Dhu al-Hijjah (second departure) in Mina.",
            ["rituals.h6t"] = "6. Tawaf al-Ifadah",
            ["rituals.h6d"] = "A pillar of hajj — 7 circuits after the first tahallul, followed by the hajj sa'i (for tamattu').",
            ["rituals.h7t"] = "7. Tawaf al-Wada (Farewell)",
            ["rituals.h7d"] = "The farewell tawaf before leaving Makkah. Obligatory for pilgrims who are not residents of Makkah.",

            ["rit.Ihram"] = "Ihram & Intention", ["rit.Thawaf"] = "Tawaf", ["rit.Sai"] = "Sa'i",
            ["rit.Tahalul"] = "Tahallul", ["rit.WukufArafah"] = "Standing at Arafah",
            ["rit.MabitMuzdalifah"] = "Overnight at Muzdalifah", ["rit.LemparJumrah"] = "Stoning the Jamarat",
            ["rit.MabitMina"] = "Overnight in Mina", ["rit.ThawafIfadah"] = "Tawaf al-Ifadah",
            ["rit.ThawafWada"] = "Farewell Tawaf", ["rit.ZiarahNabawi"] = "Visit to Nabawi",
            ["zone.mataf"] = "Tawaf Area (Mataf)", ["zone.masaa"] = "Sa'i Area (Mas'a)",
            ["zone.mosque"] = "Masjid al-Haram", ["zone.arafah"] = "Plain of Arafah",
            ["zone.muzdalifah"] = "Muzdalifah", ["zone.mina"] = "Mina / Jamarat",
            ["zone.nabawi"] = "Masjid an-Nabawi", ["zone.raudhah"] = "Rawdah",

            ["chat.pageTitle"] = "Haji Sule — HajjVR",
            ["chat.subtitle"] = "your worship assistant",
            ["chat.modelActive"] = "Active model",
            ["chat.newSession"] = "➕ New Session",
            ["chat.deleteSession"] = "Delete session",
            ["chat.resetSession"] = "🧹 Reset This Session",
            ["chat.greeting"] = "Assalamu'alaikum! Sule here, ready to help!",
            ["chat.greetingText"] = "Ask anything: how to perform tawaf, sa'i duas, current mataf crowding, pilgrim progress, exchange rates, even the latest news. Attach images/documents if needed.",
            ["chat.you"] = "🙋 You",
            ["chat.attach"] = "Attach image/document",
            ["chat.placeholder"] = "Type your question… (Enter to send, Shift+Enter for new line)",
            ["chat.newTitle"] = "New Conversation",

            ["map.pageTitle"] = "Interactive Map — HajjVR",
            ["map.title"] = "🗺️ Interactive Map",
            ["map.makkah"] = "🕋 Makkah", ["map.madinah"] = "🕌 Madinah",
            ["map.open3d"] = "🕶️ Open 3D Mode",
            ["map.catMasjid"] = "Mosque", ["map.catRitual"] = "Ritual", ["map.catZiarah"] = "Visits", ["map.catFacility"] = "Facility",
            ["map.selectHint"] = "👆 Click a location on the map to see details.",
            ["map.viewIn3d"] = "🕶️ View in 3D",
            ["map.allLocations"] = "📍 All Locations",

            ["search.pageTitle"] = "Search — HajjVR",
            ["search.title"] = "🔎 Semantic Search",
            ["search.subtitle"] = "Search ritual guides, holy sites, and documents.",
            ["search.modeVec"] = "Mode: vector embedding 🧠",
            ["search.modeKw"] = "Mode: keyword (set Embedding:ApiKey for vector mode)",
            ["search.placeholder"] = "e.g. how to perform tawaf? what is the Rawdah?",
            ["search.noResults"] = "No results for",
            ["search.score"] = "score",

            ["lb.pageTitle"] = "Leaderboard — HajjVR",
            ["lb.title"] = "🏆 Pilgrim Leaderboard",
            ["lb.subtitle"] = "Points = badge points + 10 points per completed ritual. Worship with spirit, not just to compete! 😊",
            ["lb.name"] = "Name", ["lb.group"] = "Group", ["lb.badge"] = "Badges",
            ["lb.ritualsDone"] = "Rituals Done", ["lb.points"] = "Points",

            ["rep.pageTitle"] = "Reports — HajjVR",
            ["rep.title"] = "📑 Pilgrim Journey Reports",
            ["rep.searchPh"] = "Search pilgrim name…",
            ["rep.allGroups"] = "All groups",
            ["rep.name"] = "Name", ["rep.group"] = "Group", ["rep.package"] = "Package",
            ["rep.progress"] = "Progress",
            ["rep.downloadPdf"] = "Download individual PDF report",

            ["jl.pageTitle"] = "Pilgrim Data — HajjVR",
            ["jl.title"] = "🧕 Pilgrim Data",
            ["jl.searchPh"] = "Search name / group…",
            ["jl.name"] = "Name", ["jl.username"] = "Username", ["jl.group"] = "Group", ["jl.package"] = "Package",
            ["jl.nationality"] = "Nationality", ["jl.phone"] = "Phone",
            ["jl.detail"] = "Details →",

            ["jd.pageTitle"] = "Pilgrim Details — HajjVR",
            ["jd.pdf"] = "📄 PDF Report",
            ["jd.profile"] = "Profile", ["jd.group"] = "Group", ["jd.package"] = "Package",
            ["jd.passport"] = "Passport No.", ["jd.nationality"] = "Nationality", ["jd.phone"] = "Phone",
            ["jd.notes"] = "Notes", ["jd.save"] = "💾 Save", ["jd.saved"] = "✅ Saved",
            ["jd.progress"] = "Ritual Progress",
            ["jd.docs"] = "📂 Documents & Attachments", ["jd.upload"] = "⬆️ Upload Document",
            ["jd.colTitle"] = "Title", ["jd.colType"] = "Type", ["jd.colSize"] = "Size", ["jd.colUploaded"] = "Uploaded",
            ["jd.kindImg"] = "Image", ["jd.kindVideo"] = "Video", ["jd.kindDoc"] = "Document",

            ["prof.pageTitle"] = "Profile — HajjVR",
            ["prof.title"] = "👤 My Profile",
            ["prof.bio"] = "Personal Data", ["prof.fullName"] = "Full Name", ["prof.email"] = "Email",
            ["prof.avatar"] = "Profile Photo", ["prof.save"] = "💾 Save", ["prof.saved"] = "✅ Saved",
            ["prof.changePass"] = "Change Password", ["prof.oldPass"] = "Old Password",
            ["prof.newPass"] = "New Password (min. 6)", ["prof.changePassBtn"] = "🔐 Change Password",
            ["prof.passShort"] = "❌ New password must be at least 6 characters.",
            ["prof.passOk"] = "✅ Password changed successfully.",
            ["prof.passWrong"] = "❌ Old password is incorrect.",
            ["prof.badges"] = "🏅 My Badges", ["prof.points"] = "points",

            ["sett.pageTitle"] = "Settings — HajjVR",
            ["sett.title"] = "⚙️ Application Settings",
            ["sett.subtitle"] = "Values here override appsettings.json (stored in the database, applied without restart).",
            ["sett.llm"] = "🧠 AI Model (Haji Sule)",
            ["sett.provider"] = "Provider", ["sett.model"] = "Model", ["sett.apiKey"] = "API Key",
            ["sett.endpoint"] = "Endpoint (optional, OpenAI-compatible)",
            ["sett.temperature"] = "Temperature", ["sett.maxTokens"] = "Max Tokens",
            ["sett.systemPrompt"] = "System Prompt (Haji Sule persona)",
            ["sett.sysPromptPh"] = "Leave empty for the default persona",
            ["sett.storage"] = "📦 File Storage",
            ["sett.storageFs"] = "File System (default)",
            ["sett.azureCs"] = "Connection String",
            ["sett.accessKey"] = "Access Key", ["sett.secretKey"] = "Secret Key",
            ["sett.bucket"] = "Bucket", ["sett.serviceUrl"] = "Service URL (MinIO)",
            ["sett.integration"] = "🔌 Integrations",
            ["sett.tavily"] = "Tavily API Key (chatbot web search)",
            ["sett.restKey"] = "REST API Key (X-Api-Key header)",
            ["sett.embeddingKey"] = "Embedding API Key (vector semantic search)",
            ["sett.embeddingPh"] = "empty = keyword mode",
            ["sett.dbActive"] = "🗄️ Active database:",
            ["sett.dbChange"] = "Change the database provider via appsettings.json → Database:Provider (SQLite / SQLServer / MySQL / PostgreSQL) then restart the app.",
            ["sett.saveAll"] = "💾 Save All",
            ["sett.saved"] = "✅ Saved & active now",

            ["users.pageTitle"] = "Users — HajjVR",
            ["users.title"] = "👥 User Management",
            ["users.newUser"] = "➕ New User",
            ["users.newUserTitle"] = "New User",
            ["users.username"] = "Username", ["users.fullName"] = "Full name", ["users.email"] = "Email", ["users.password"] = "Password",
            ["users.allRoles"] = "All roles",
            ["users.name"] = "Name", ["users.role"] = "Role", ["users.status"] = "Status", ["users.created"] = "Created",
            ["users.active"] = "Active", ["users.inactive"] = "Inactive",
            ["users.errRequired"] = "Username is required & password must be at least 6 characters.",
            ["users.errExists"] = "Username already taken.",

            ["st.pageTitle"] = "Stress Test — HajjVR",
            ["st.title"] = "⚡ Stress Test Crowd Simulation",
            ["st.subtitle"] = "Test rendering performance with thousands of parallel pilgrims. Raise the agent count until FPS drops to find your device's limit.",
            ["st.fpsHistory"] = "📉 FPS History (60s)",

            ["nf.title"] = "Page Not Found",
            ["nf.desc"] = "Sorry, the content you are looking for does not exist.",
            ["nf.home"] = "← Back to Home",

            ["err.title"] = "Error.",
            ["err.msg"] = "An error occurred while processing your request.",
            ["err.requestId"] = "Request ID:",

            ["rc.rejoining"] = "Rejoining the server...",
            ["rc.rejoinFail"] = "Rejoin failed... trying again in <span id=\"components-seconds-to-next-attempt\"></span> seconds.",
            ["rc.failed"] = "Failed to rejoin.<br />Please retry or reload the page.",
            ["rc.retry"] = "Retry",
            ["rc.paused"] = "The session has been paused by the server.",
            ["rc.resumeFailed"] = "Failed to resume the session.<br />Please retry or reload the page.",
            ["rc.resume"] = "Resume",

            ["errUi.title"] = "An unexpected error has occurred.",
            ["errUi.reload"] = "Reload",

            ["common.save"] = "Save", ["common.cancel"] = "Cancel", ["common.delete"] = "Delete",
            ["common.search"] = "Search", ["common.export.pdf"] = "Export PDF", ["common.export.excel"] = "Export Excel",
            ["common.openMenu"] = "Open menu", ["common.theme"] = "Toggle theme", ["common.profile"] = "Profile",
            ["common.language"] = "Select language",
            ["common.loading"] = "Loading…", ["common.back"] = "← Back",
            ["dash.totalJamaah"] = "Total Pilgrims", ["dash.avgProgress"] = "Average Progress",
            ["dash.completedUmrah"] = "Umrah Completed", ["dash.activeNow"] = "24h Activity",
            ["dash.heatmap"] = "Crowd Heatmap", ["dash.progressByRitual"] = "Progress by Ritual",
        },
        ["ar"] = new()
        {
            ["app.title"] = "HajjVR — محاكي الحج والعمرة",
            ["app.subtitle"] = "محاكي الحج والعمرة",
            ["nav.home"] = "الرئيسية", ["nav.dashboard"] = "لوحة التحكم", ["nav.simulation"] = "محاكاة ثلاثية الأبعاد",
            ["nav.map"] = "الخريطة التفاعلية", ["nav.rituals"] = "دليل المناسك", ["nav.chat"] = "الحاج سولي",
            ["nav.reports"] = "التقارير", ["nav.jamaah"] = "الحجاج", ["nav.leaderboard"] = "لوحة الصدارة",
            ["nav.search"] = "بحث", ["nav.settings"] = "الإعدادات", ["nav.users"] = "المستخدمون",
            ["nav.stress"] = "اختبار الضغط", ["nav.login"] = "تسجيل الدخول", ["nav.logout"] = "تسجيل الخروج", ["nav.profile"] = "الملف الشخصي",
            ["nav.groupSim"] = "المحاكاة", ["nav.groupAsst"] = "المساعد", ["nav.groupComm"] = "المجتمع",
            ["nav.groupMgmt"] = "الإدارة", ["nav.groupSys"] = "النظام",

            ["home.pageTitle"] = "HajjVR — الرئيسية",
            ["home.welcome"] = "مرحباً بكم في HajjVR",
            ["home.badge"] = "✦ تجربة عبادة افتراضية ✦",
            ["home.tagline"] = "محاكي تفاعلي ثلاثي الأبعاد للحج والعمرة — تعلم المناسك بتجربة غامرة.",
            ["home.ctaStart"] = "🕋 ابدأ المحاكاة ثلاثية الأبعاد",
            ["home.ctaChat"] = "💬 اسأل الحاج سولي",
            ["home.ctaRituals"] = "📿 دليل المناسك",
            ["home.ctaLogin"] = "🔑 سجّل الدخول للبدء",
            ["home.explore"] = "استكشف الميزات",
            ["home.f1t"] = "المسجد الحرام ثلاثي الأبعاد",
            ["home.f1d"] = "الكعبة، ومنطقة الطواف (المطاف)، وممر السعي من الصفا إلى المروة، مع محاكاة فورية لآلاف الحجاج.",
            ["home.f2t"] = "المسجد النبوي",
            ["home.f2d"] = "استكشف الروضة ومقام النبي ﷺ ومناطق العبادة بأنماط كاميرا الشخص الأول والثالث والمنظر العلوي.",
            ["home.f3t"] = "مناسك الحج",
            ["home.f3d"] = "الوقوف بعرفة، والمبيت بمزدلفة، ورمي الجمرات في منى — كل مناسك الحج في محاكاة تفاعلية واحدة.",
            ["home.f4t"] = "روبوت الحاج سولي",
            ["home.f4d"] = "مساعد ذكاء اصطناعي متعدد النماذج (OpenAI وAnthropic وGemini وOllama) يفهم المناسك ويبحث في الإنترنت ويحسب ويستعلم عن بيانات الحجاج.",
            ["home.f5t"] = "لوحة التحكم والتقارير",
            ["home.f5d"] = "إحصائيات الحجاج وخريطة الازدحام الحرارية وتقدم العبادة وتصدير التقارير إلى PDF/Excel للمرشدين والمشغلين.",
            ["home.f6t"] = "الألعاب والتحفيز",
            ["home.f6d"] = "اجمع الشارات وتابع التقدم وتنافس في لوحة صدارة الحجاج.",
            ["home.demo"] = "💡 حسابات تجريبية:",

            ["login.pageTitle"] = "تسجيل الدخول — HajjVR",
            ["login.title"] = "تسجيل الدخول",
            ["login.subtitle"] = "محاكي الحج والعمرة ثلاثي الأبعاد",
            ["login.username"] = "اسم المستخدم",
            ["login.password"] = "كلمة المرور",
            ["login.usernamePh"] = "مثال: admin",
            ["login.submit"] = "🔑 دخول",
            ["login.forgot"] = "نسيت كلمة المرور؟",
            ["login.error"] = "اسم المستخدم أو كلمة المرور غير صحيحة.",
            ["login.demo"] = "تجريبي:",

            ["fp.pageTitle"] = "إعادة تعيين كلمة المرور — HajjVR",
            ["fp.title"] = "🔐 نسيت كلمة المرور",
            ["fp.hint"] = "أدخل اسم المستخدم أو البريد الإلكتروني. في الوضع التجريبي يظهر رابط إعادة التعيين هنا مباشرة (بدون بريد إلكتروني).",
            ["fp.identity"] = "اسم المستخدم / البريد الإلكتروني",
            ["fp.identityPh"] = "مثال: jamaah01",
            ["fp.submit"] = "إنشاء رابط إعادة التعيين",
            ["fp.created"] = "✅ تم إنشاء رابط إعادة التعيين (صالح لمدة ساعة):",
            ["fp.notFound"] = "❌ المستخدم غير موجود.",
            ["fp.back"] = "← العودة إلى تسجيل الدخول",

            ["rp.pageTitle"] = "كلمة مرور جديدة — HajjVR",
            ["rp.title"] = "🔑 تعيين كلمة مرور جديدة",
            ["rp.done"] = "✅ تم تغيير كلمة المرور بنجاح.",
            ["rp.loginNow"] = "سجّل الدخول الآن ←",
            ["rp.token"] = "رمز إعادة التعيين",
            ["rp.newPassword"] = "كلمة المرور الجديدة (٦ أحرف على الأقل)",
            ["rp.submit"] = "حفظ كلمة المرور",
            ["rp.error"] = "❌ الرمز غير صالح أو منتهي الصلاحية، أو كلمة المرور قصيرة جداً.",

            ["sim.pageTitle"] = "المحاكاة ثلاثية الأبعاد — HajjVR",
            ["sim.title"] = "🕶️ المحاكاة ثلاثية الأبعاد",
            ["sim.badge"] = "🕐 {0} · {1} FPS · {2} حاج",
            ["sim.hud"] = "FPS: {0} · الحجاج: {1} · الرسم: {2} · 🕐 {3}",
            ["sim.sceneHaram"] = "🕋 المسجد الحرام",
            ["sim.sceneNabawi"] = "🕌 المسجد النبوي",
            ["sim.sceneManasik"] = "⛰️ مناسك الحج",
            ["sim.focus"] = "التركيز:",
            ["sim.timeLabel"] = "وقت المحاكاة",
            ["sim.camOrbit"] = "🎥 مدار", ["sim.camBird"] = "🦅 منظر علوي",
            ["sim.camFp"] = "👁️ الشخص الأول", ["sim.camTp"] = "🚶 الشخص الثالث",
            ["sim.resetCam"] = "🎯 إعادة تعيين",
            ["sim.fullscreen"] = "⛶ ملء الشاشة",
            ["sim.tSubuh"] = "🌅 الفجر", ["sim.tSiang"] = "☀️ الظهر",
            ["sim.tMaghrib"] = "🌇 المغرب", ["sim.tMalam"] = "🌙 الليل",
            ["sim.autoCycle"] = "🔄 دورة ٢٤ ساعة",
            ["sim.stopCycle"] = "⏹ إيقاف الدورة",
            ["sim.crowd"] = "👥 الحجاج:",
            ["sim.speed"] = "⏩ السرعة:",
            ["sim.pause"] = "⏸ إيقاف مؤقت", ["sim.resume"] = "▶ متابعة",
            ["sim.shadowsOn"] = "🌗 الظلال: تشغيل", ["sim.shadowsOff"] = "🌗 الظلال: إيقاف",
            ["sim.guide"] = "📖 الدليل", ["sim.controls"] = "⌨️ التحكم",
            ["sim.controlsTitle"] = "⌨️ التحكم",
            ["sim.bOrbit"] = "مدار", ["sim.bFp"] = "الشخص الأول", ["sim.bTp"] = "الشخص الثالث", ["sim.bVr"] = "VR",
            ["sim.helpOrbit"] = "سحب = تدوير، تمرير = تكبير، زر أيمن = تحريك",
            ["sim.helpFp"] = "انقر على الشاشة → WASD/الأسهم للمشي، Shift للركض، Esc للخروج",
            ["sim.helpTp"] = "يتبع أحد الحجاج تلقائياً",
            ["sim.helpVr"] = "زر \"Enter VR\" بالأسفل (نظارة WebXR)",
            ["sim.guideHaram"] = "🕋 الطواف والسعي",
            ["sim.guideNabawi"] = "🕌 زيارة المسجد النبوي",
            ["sim.guideManasik"] = "⛰️ تسلسل الحج",
            ["sim.h1"] = "ابدأ الطواف من الخط البني المحاذي للحجر الأسود (الزاوية الشرقية للكعبة) مع إبقاء الكعبة على يسارك.",
            ["sim.h2"] = "طف حول الكعبة ٧ أشواط عكس اتجاه عقارب الساعة.",
            ["sim.h3"] = "صلِّ ركعتين خلف مقام إبراهيم (القبة الكريستالية الذهبية).",
            ["sim.h4"] = "اشرب ماء زمزم.",
            ["sim.h5"] = "السعي: الممر الطويل في الجهة الشرقية — من الصفا (الجنوب الشرقي) إلى المروة (الشمال الشرقي)، ٧ أشواط.",
            ["sim.h6"] = "اركض هرولة بين الضوءين الأخضرين في منتصف الممر (للرجال).",
            ["sim.n1"] = "ادخل المسجد بالقدم اليمنى واقرأ دعاء دخول المسجد.",
            ["sim.n2"] = "صلِّ ركعتي تحية المسجد.",
            ["sim.n3"] = "توجه إلى الروضة (المنطقة الخضراء قرب القبة الخضراء) إن أمكن.",
            ["sim.n4"] = "سلّم على النبي ﷺ وأبي بكر وعمر بهدوء.",
            ["sim.m1"] = "٨ ذو الحجة: التوجه إلى منى (مدينة الخيام في الشرق) والمبيت فيها.",
            ["sim.m2"] = "٩ ذو الحجة: الوقوف بعرفة (الغرب، قرب جبل الرحمة) حتى غروب الشمس.",
            ["sim.m3"] = "ليلة ١٠: المبيت بمزدلفة وجمع ٤٩–٧٠ حصاة.",
            ["sim.m4"] = "١٠ ذو الحجة: رمي جمرة العقبة في جسر الجمرات ثم التحلل.",
            ["sim.m5"] = "١١–١٣ ذو الحجة: المبيت بمنى ورمي الجمرات الثلاث كل يوم.",

            ["dash.pageTitle"] = "لوحة التحكم — HajjVR",
            ["dash.autoRefresh"] = "🔄 تحديث تلقائي كل ٣٠ ثانية",
            ["dash.mentors"] = "{0} مرشد",
            ["dash.hajiDone"] = "{0} حج مكتمل",
            ["dash.chatSessions"] = "{0} جلسة محادثة",
            ["dash.done"] = "مكتمل", ["dash.inProgress"] = "قيد التنفيذ", ["dash.notStarted"] = "لم يبدأ",
            ["dash.crowdNow"] = "👥 الازدحام الحالي",
            ["dash.heatmapTitle"] = "🔥 خريطة الازدحام (٢٤ ساعة)",
            ["dash.people"] = "شخص",

            ["rituals.pageTitle"] = "دليل المناسك — HajjVR",
            ["rituals.title"] = "📿 دليل المناسك التفاعلي",
            ["rituals.umrah"] = "🌙 عمرة", ["rituals.haji"] = "🏔️ حج",
            ["rituals.newBadge"] = "🎉 شارة جديدة!",
            ["rituals.overall"] = "التقدم الكلي",
            ["rituals.progressFmt"] = "{0} من {1} مناسك {2} مكتملة ({3}%)",
            ["rituals.wordU"] = "العمرة", ["rituals.wordH"] = "الحج",
            ["rituals.start"] = "▶ ابدأ", ["rituals.markDone"] = "✔ علّم كمكتمل", ["rituals.repeat"] = "↺ إعادة",
            ["rituals.u1t"] = "١. الإحرام من الميقات",
            ["rituals.u1d"] = "اغتسل والبس ملابس الإحرام (قطعتان غير مخيطة للرجال) وانوِ العمرة من الميقات (مثل بئر علي لمن يأتي من المدينة). واجتنب محظورات الإحرام.",
            ["rituals.u2t"] = "٢. الطواف ٧ أشواط",
            ["rituals.u2d"] = "طف حول الكعبة ٧ أشواط عكس اتجاه عقارب الساعة بدءاً من خط الحجر الأسود مع إبقاء الكعبة على يسارك. يُسن للرجال الرمل (الإسراع) في الأشواط الثلاثة الأولى.",
            ["rituals.u3t"] = "٣. السعي بين الصفا والمروة",
            ["rituals.u3d"] = "امشِ ٧ أشواط من الصفا إلى المروة (٣٫١٥ كم تقريباً). يهرول الرجال بين الضوءين الأخضرين. وينتهي السعي عند المروة.",
            ["rituals.u4t"] = "٤. التحلل",
            ["rituals.u4d"] = "احلق الرأس (الأفضل للرجال) أو قصّر الشعر بمقدار ٣ شعرات على الأقل. بذلك تكتمل العمرة ويزول حظر الإحرام.",
            ["rituals.u5t"] = "٥. زيارة المدينة (سنة)",
            ["rituals.u5d"] = "صلِّ في المسجد النبوي (يعادل ألف صلاة)، وادعُ في الروضة، وسلّم على النبي ﷺ. ليست من أركان العمرة لكنها مستحبة بشدة.",
            ["rituals.h1t"] = "١. إحرام الحج (٨ ذو الحجة)",
            ["rituals.h1d"] = "انوِ الحج من مكان الإقامة (للمتمتع) ثم توجّه إلى منى للمبيت يوم التروية.",
            ["rituals.h2t"] = "٢. الوقوف بعرفة (٩ ذو الحجة)",
            ["rituals.h2d"] = "أهم ركن — «الحج عرفة». من الزوال حتى غروب الشمس. أكثِر من الدعاء والذكر والاستغفار.",
            ["rituals.h3t"] = "٣. المبيت بمزدلفة",
            ["rituals.h3d"] = "بت ليلة بعد المغرب حتى منتصف الليل. اجمع ٤٩–٧٠ حصاة لرمي الجمرات.",
            ["rituals.h4t"] = "٤. رمي الجمرات",
            ["rituals.h4d"] = "١٠ ذو الحجة: رمي جمرة العقبة ٧ حصيات. ١١–١٣ ذو الحجة: رمي الجمرات الثلاث (الصغرى والوسطى والعقبة) ٧ حصيات لكل منها بعد الزوال.",
            ["rituals.h5t"] = "٥. المبيت بمنى (أيام التشريق)",
            ["rituals.h5d"] = "بت في منى ليلة ١١ و١٢ (النفر الأول) أو حتى ١٣ ذو الحجة (النفر الثاني).",
            ["rituals.h6t"] = "٦. طواف الإفاضة",
            ["rituals.h6d"] = "ركن من أركان الحج — طواف ٧ أشواط بعد التحلل الأول، يتبعه سعي الحج (للمتمتع).",
            ["rituals.h7t"] = "٧. طواف الوداع",
            ["rituals.h7d"] = "طواف الوداع قبل مغادرة مكة. واجب على غير أهل مكة.",

            ["rit.Ihram"] = "الإحرام والنية", ["rit.Thawaf"] = "الطواف", ["rit.Sai"] = "السعي",
            ["rit.Tahalul"] = "التحلل", ["rit.WukufArafah"] = "الوقوف بعرفة",
            ["rit.MabitMuzdalifah"] = "المبيت بمزدلفة", ["rit.LemparJumrah"] = "رمي الجمرات",
            ["rit.MabitMina"] = "المبيت بمنى", ["rit.ThawafIfadah"] = "طواف الإفاضة",
            ["rit.ThawafWada"] = "طواف الوداع", ["rit.ZiarahNabawi"] = "زيارة المسجد النبوي",
            ["zone.mataf"] = "منطقة الطواف (المطاف)", ["zone.masaa"] = "منطقة السعي (المسعى)",
            ["zone.mosque"] = "المسجد الحرام", ["zone.arafah"] = "صعيد عرفة",
            ["zone.muzdalifah"] = "مزدلفة", ["zone.mina"] = "منى / الجمرات",
            ["zone.nabawi"] = "المسجد النبوي", ["zone.raudhah"] = "الروضة",

            ["chat.pageTitle"] = "الحاج سولي — HajjVR",
            ["chat.subtitle"] = "مساعدك في العبادة",
            ["chat.modelActive"] = "النموذج النشط",
            ["chat.newSession"] = "➕ جلسة جديدة",
            ["chat.deleteSession"] = "حذف الجلسة",
            ["chat.resetSession"] = "🧹 إعادة تعيين هذه الجلسة",
            ["chat.greeting"] = "السلام عليكم! أنا سولي هنا وجاهز للمساعدة!",
            ["chat.greetingText"] = "اسأل عن أي شيء: طريقة الطواف، أدعية السعي، ازدحام المطاف الآن، تقدم الحجاج، أسعار الصرف، وحتى آخر الأخبار. يمكنك إرفاق الصور والمستندات عند الحاجة.",
            ["chat.you"] = "🙋 أنت",
            ["chat.attach"] = "إرفاق صورة/مستند",
            ["chat.placeholder"] = "اكتب سؤالك… (Enter للإرسال، Shift+Enter لسطر جديد)",
            ["chat.newTitle"] = "محادثة جديدة",

            ["map.pageTitle"] = "الخريطة التفاعلية — HajjVR",
            ["map.title"] = "🗺️ الخريطة التفاعلية",
            ["map.makkah"] = "🕋 مكة", ["map.madinah"] = "🕌 المدينة",
            ["map.open3d"] = "🕶️ فتح الوضع ثلاثي الأبعاد",
            ["map.catMasjid"] = "مسجد", ["map.catRitual"] = "منسك", ["map.catZiarah"] = "زيارة", ["map.catFacility"] = "مرافق",
            ["map.selectHint"] = "👆 انقر أي نقطة على الخريطة لعرض التفاصيل.",
            ["map.viewIn3d"] = "🕶️ عرض ثلاثي الأبعاد",
            ["map.allLocations"] = "📍 جميع المواقع",

            ["search.pageTitle"] = "بحث — HajjVR",
            ["search.title"] = "🔎 البحث الدلالي",
            ["search.subtitle"] = "ابحث في أدلة المناسك والمواقع المقدسة والمستندات.",
            ["search.modeVec"] = "الوضع: تضمين متجهي 🧠",
            ["search.modeKw"] = "الوضع: كلمات مفتاحية (اضبط Embedding:ApiKey للوضع المتجهي)",
            ["search.placeholder"] = "مثال: كيف يؤدي الطواف؟ ما هي الروضة؟",
            ["search.noResults"] = "لا توجد نتائج لـ",
            ["search.score"] = "الدرجة",

            ["lb.pageTitle"] = "لوحة الصدارة — HajjVR",
            ["lb.title"] = "🏆 لوحة صدارة الحجاج",
            ["lb.subtitle"] = "النقاط = نقاط الشارات + ١٠ نقاط لكل منسك مكتمل. أخلص في العبادة لا للمنافسة فقط! 😊",
            ["lb.name"] = "الاسم", ["lb.group"] = "المجموعة", ["lb.badge"] = "الشارات",
            ["lb.ritualsDone"] = "المناسك المكتملة", ["lb.points"] = "النقاط",

            ["rep.pageTitle"] = "التقارير — HajjVR",
            ["rep.title"] = "📑 تقارير رحلة الحجاج",
            ["rep.searchPh"] = "ابحث عن اسم الحاج…",
            ["rep.allGroups"] = "جميع المجموعات",
            ["rep.name"] = "الاسم", ["rep.group"] = "المجموعة", ["rep.package"] = "الباقة",
            ["rep.progress"] = "التقدم",
            ["rep.downloadPdf"] = "تحميل تقرير PDF فردي",

            ["jl.pageTitle"] = "بيانات الحجاج — HajjVR",
            ["jl.title"] = "🧕 بيانات الحجاج",
            ["jl.searchPh"] = "ابحث عن اسم / مجموعة…",
            ["jl.name"] = "الاسم", ["jl.username"] = "اسم المستخدم", ["jl.group"] = "المجموعة", ["jl.package"] = "الباقة",
            ["jl.nationality"] = "الجنسية", ["jl.phone"] = "الهاتف",
            ["jl.detail"] = "التفاصيل ←",

            ["jd.pageTitle"] = "تفاصيل الحاج — HajjVR",
            ["jd.pdf"] = "📄 تقرير PDF",
            ["jd.profile"] = "الملف الشخصي", ["jd.group"] = "المجموعة", ["jd.package"] = "الباقة",
            ["jd.passport"] = "رقم الجواز", ["jd.nationality"] = "الجنسية", ["jd.phone"] = "الهاتف",
            ["jd.notes"] = "ملاحظات", ["jd.save"] = "💾 حفظ", ["jd.saved"] = "✅ تم الحفظ",
            ["jd.progress"] = "تقدم المناسك",
            ["jd.docs"] = "📂 المستندات والمرفقات", ["jd.upload"] = "⬆️ رفع مستند",
            ["jd.colTitle"] = "العنوان", ["jd.colType"] = "النوع", ["jd.colSize"] = "الحجم", ["jd.colUploaded"] = "تاريخ الرفع",
            ["jd.kindImg"] = "صورة", ["jd.kindVideo"] = "فيديو", ["jd.kindDoc"] = "مستند",

            ["prof.pageTitle"] = "الملف الشخصي — HajjVR",
            ["prof.title"] = "👤 ملفي الشخصي",
            ["prof.bio"] = "البيانات الشخصية", ["prof.fullName"] = "الاسم الكامل", ["prof.email"] = "البريد الإلكتروني",
            ["prof.avatar"] = "صورة الملف الشخصي", ["prof.save"] = "💾 حفظ", ["prof.saved"] = "✅ تم الحفظ",
            ["prof.changePass"] = "تغيير كلمة المرور", ["prof.oldPass"] = "كلمة المرور القديمة",
            ["prof.newPass"] = "كلمة مرور جديدة (٦ أحرف على الأقل)", ["prof.changePassBtn"] = "🔐 تغيير كلمة المرور",
            ["prof.passShort"] = "❌ يجب ألا تقل كلمة المرور الجديدة عن ٦ أحرف.",
            ["prof.passOk"] = "✅ تم تغيير كلمة المرور بنجاح.",
            ["prof.passWrong"] = "❌ كلمة المرور القديمة غير صحيحة.",
            ["prof.badges"] = "🏅 شاراتي", ["prof.points"] = "نقطة",

            ["sett.pageTitle"] = "الإعدادات — HajjVR",
            ["sett.title"] = "⚙️ إعدادات التطبيق",
            ["sett.subtitle"] = "القيم هنا تتجاوز appsettings.json (تُحفظ في قاعدة البيانات وتُطبَّق دون إعادة تشغيل).",
            ["sett.llm"] = "🧠 نموذج الذكاء الاصطناعي (الحاج سولي)",
            ["sett.provider"] = "المزوّد", ["sett.model"] = "النموذج", ["sett.apiKey"] = "مفتاح API",
            ["sett.endpoint"] = "النقطة الطرفية (اختياري، متوافقة مع OpenAI)",
            ["sett.temperature"] = "درجة الحرارة", ["sett.maxTokens"] = "الحد الأقصى للرموز",
            ["sett.systemPrompt"] = "الموجه النظامي (شخصية الحاج سولي)",
            ["sett.sysPromptPh"] = "اتركه فارغاً للشخصية الافتراضية",
            ["sett.storage"] = "📦 تخزين الملفات",
            ["sett.storageFs"] = "نظام الملفات (الافتراضي)",
            ["sett.azureCs"] = "سلسلة الاتصال",
            ["sett.accessKey"] = "مفتاح الوصول", ["sett.secretKey"] = "المفتاح السري",
            ["sett.bucket"] = "الحاوية", ["sett.serviceUrl"] = "رابط الخدمة (MinIO)",
            ["sett.integration"] = "🔌 التكاملات",
            ["sett.tavily"] = "مفتاح Tavily (بحث الإنترنت للروبوت)",
            ["sett.restKey"] = "مفتاح REST API (ترويسة X-Api-Key)",
            ["sett.embeddingKey"] = "مفتاح التضمين (البحث الدلالي المتجهي)",
            ["sett.embeddingPh"] = "فارغ = وضع الكلمات المفتاحية",
            ["sett.dbActive"] = "🗄️ قاعدة البيانات النشطة:",
            ["sett.dbChange"] = "غيّر مزوّد قاعدة البيانات عبر appsettings.json ← Database:Provider (SQLite / SQLServer / MySQL / PostgreSQL) ثم أعد تشغيل التطبيق.",
            ["sett.saveAll"] = "💾 حفظ الكل",
            ["sett.saved"] = "✅ تم الحفظ وهو فعّال الآن",

            ["users.pageTitle"] = "المستخدمون — HajjVR",
            ["users.title"] = "👥 إدارة المستخدمين",
            ["users.newUser"] = "➕ مستخدم جديد",
            ["users.newUserTitle"] = "مستخدم جديد",
            ["users.username"] = "اسم المستخدم", ["users.fullName"] = "الاسم الكامل", ["users.email"] = "البريد الإلكتروني", ["users.password"] = "كلمة المرور",
            ["users.allRoles"] = "جميع الأدوار",
            ["users.name"] = "الاسم", ["users.role"] = "الدور", ["users.status"] = "الحالة", ["users.created"] = "تاريخ الإنشاء",
            ["users.active"] = "نشط", ["users.inactive"] = "غير نشط",
            ["users.errRequired"] = "اسم المستخدم مطلوب وكلمة المرور ٦ أحرف على الأقل.",
            ["users.errExists"] = "اسم المستخدم مستخدم بالفعل.",

            ["st.pageTitle"] = "اختبار الضغط — HajjVR",
            ["st.title"] = "⚡ اختبار ضغط محاكاة الحشود",
            ["st.subtitle"] = "اختبر أداء العرض مع آلاف الحجاج المتوازيين. ارفع عدد الوكلاء حتى ينخفض معدل الإطارات لمعرفة حد جهازك.",
            ["st.fpsHistory"] = "📉 سجل الإطارات (٦٠ ثانية)",

            ["nf.title"] = "الصفحة غير موجودة",
            ["nf.desc"] = "عذراً، المحتوى الذي تبحث عنه غير موجود.",
            ["nf.home"] = "← العودة إلى الرئيسية",

            ["err.title"] = "خطأ.",
            ["err.msg"] = "حدث خطأ أثناء معالجة طلبك.",
            ["err.requestId"] = "معرّف الطلب:",

            ["rc.rejoining"] = "إعادة الاتصال بالخادم...",
            ["rc.rejoinFail"] = "فشلت إعادة الاتصال... المحاولة مرة أخرى خلال <span id=\"components-seconds-to-next-attempt\"></span> ثانية.",
            ["rc.failed"] = "فشلت إعادة الاتصال.<br />يرجى إعادة المحاولة أو تحديث الصفحة.",
            ["rc.retry"] = "إعادة المحاولة",
            ["rc.paused"] = "تم إيقاف الجلسة مؤقتاً بواسطة الخادم.",
            ["rc.resumeFailed"] = "فشل استئناف الجلسة.<br />يرجى إعادة المحاولة أو تحديث الصفحة.",
            ["rc.resume"] = "متابعة",

            ["errUi.title"] = "حدث خطأ غير متوقع.",
            ["errUi.reload"] = "إعادة التحميل",

            ["common.save"] = "حفظ", ["common.cancel"] = "إلغاء", ["common.delete"] = "حذف",
            ["common.search"] = "بحث", ["common.export.pdf"] = "تصدير PDF", ["common.export.excel"] = "تصدير Excel",
            ["common.openMenu"] = "فتح القائمة", ["common.theme"] = "تبديل المظهر", ["common.profile"] = "الملف الشخصي",
            ["common.language"] = "اختر اللغة",
            ["common.loading"] = "جارٍ التحميل…", ["common.back"] = "← رجوع",
            ["dash.totalJamaah"] = "إجمالي الحجاج", ["dash.avgProgress"] = "متوسط التقدم",
            ["dash.completedUmrah"] = "عمرة مكتملة", ["dash.activeNow"] = "نشاط ٢٤ ساعة",
            ["dash.heatmap"] = "خريطة الازدحام", ["dash.progressByRitual"] = "التقدم حسب المنسك",
        },
    };
}
